DROP TABLE IF EXISTS Games;
CREATE TABLE IF NOT EXISTS Games (
	GameId INTEGER PRIMARY KEY AUTOINCREMENT,
	DurableObjectId TEXT,
	DisplayGameId TEXT,
	Player1Address TEXT,
	Player2Address TEXT,
	CreatedDate DATETIME DEFAULT CURRENT_TIMESTAMP
);
