// Generated by Wrangler by running `wrangler types`

interface Env {
	ENVIRONMENT: "staging" | "production";
	CHAIN_ID: "84532" | "8453";
	BASE_TRANSPORT_URL: string;
	WALLET_PRIVATE_KEY: string;
	VERIFY_GAME_UPDATE_KEY: string;
}
