// Generated by Wrangler by running `wrangler types -e production`

interface Env {
	KV_CHESS_GAMES_BY_USER: KVNamespace;
	ENVIRONMENT: "staging" | "production";
	CHAIN_ID: "84532" | "8453";
	BASE_TRANSPORT_URL: string;
	WALLET_PRIVATE_KEY: string;
	VERIFY_GAME_UPDATE_KEY: string;
	NEYNAR_API_KEY: string;
	CHESS_GAME: DurableObjectNamespace<import("./src/index").ChessGame>;
	BUCKET_BASEDCHESS_BOARDS: R2Bucket;
	D1_GAMES: D1Database;
}
